### ISSUE TITLE
ResolvePackageNotFound in Windows 

### ISSUE THREAD

**Issue by MianWang11111** [HannesStark/self-supervised-graphs#2]
Hello, when using Anaconda in Windows 10:
I met the following question: 
Resolve Package Not Found: 
- dgl-cuda 10.2 
- torchaudio 
- pytorch-geometry
- torchvision 

I wonder whether it means I really need a computer with an NVIDIA card so that I can install cuda and cudnn, and then I can install packages above?
Great thanks.

**Comment by HannesStark** [comment]
I do not think so.
My guess is that the issue is that you do not have the channels (download sources) of pytorch and DGL added to conda.
To get the packages you listed you can follow the installation instructions here: https://pytorch.org/
and for dgl-cuda here: https://www.dgl.ai/pages/start.html (make sure to select the correct cuda version which is None if you have no GPU and the same as you have for PyTorch otherwise).

Let me know if this helps!

**Comment by MianWang11111** [comment]
Hi,  could you please tell me what model is gin.py? Graph isomorphic neural
network? Are there references?

Could you please tell me what is the model of OGBGNN? Thank you for your
help.

Hannes Stärk ***@***.***> 于2021年11月7日周日 20:56写道：
